yatube/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.create_post, name='create_post'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('auth/', include('users.urls', namespace='users')),
    path('about/', include('about.urls', namespace='about')),
    path("", include("posts.urls", namespace="Posts")),
    path("admin/", admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
]

handler403 = 'core.views.csrf_failure'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from core.models import CreatedModel
from django.db.models import UniqueConstraint


User = get_user_model()


class Group(models.Model):
    title = models.CharField('Название группы', max_length=200)
    slug = models.SlugField('Код группы', unique=True)
    description = models.TextField('Описание группы')

    class Meta:
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.title


class Post(CreatedModel):
    text = models.TextField('Текст поста', help_text='Введите текст поста')
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор поста'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Коментарии'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор коментария'
    )
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Комментарии'


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Подписка'
    )
    UniqueConstraint(fields=['user', 'author'], name='unic')

    class Meta:
        verbose_name_plural = 'Подписки'

yatube/posts/forms.py
from xml.etree.ElementTree import Comment
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image',)
        labels = {
            'text': 'Текст поста',
            'group': 'Название группы',
            'image': 'Картинка к посту',
        }
        help_texts = {
            'Text': 'Здесь можно написать текст вашего поста',
            'group': 'Группа к которой относится ваш пост',
            'image': 'Можно добавить изображение к посту',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
    labels = {
        'text': 'Текст Коментария',
    }
    help_text = {
        'text': 'Здесь можно написать комментарий',
    }

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Group, User, Comment, Follow
from django.core.paginator import Paginator
from .forms import PostForm, CommentForm
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required

POSTS_PER_PAGE = 10


def index(request):
    posts = Post.objects.all()
    paginator = Paginator(posts, POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'posts': posts,
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    paginator = Paginator(posts, POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'posts': posts,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    paginator = Paginator(posts, POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    posts_count = posts.count
    following = request.user.is_authenticated and Follow.objects.filter(
        user=request.user, author=author
    ).exists()
    context = {
        'author': author,
        'posts': posts,
        'page_obj': page_obj,
        'posts_count': posts_count,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    comments = Comment.objects.select_related('author').filter(
        post__id=post_id)
    posts_count = Post.objects.count
    form_comments = CommentForm(request.POST or None)
    context = {
        'post': post,
        'posts_count': posts_count,
        'comments': comments,
        'form_comments': form_comments
    }
    return render(request, 'posts/post_detail.html', context)


@login_required()
def create_post(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if not form.is_valid():
        return render(request, 'posts/create_post.html', {'form': form})
    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect('posts:profile', username=request.user)


@login_required()
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    context = {
        'form': form,
        'is_edit': True,
        'post_id': post,
    }
    if request.user != post.author:
        this_post = get_object_or_404(Post, pk=post_id)
        author_posts_count = Post.objects.count()
        context = {
            'this_post': this_post,
            'author_posts_count': author_posts_count,
        }
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    authors = Follow.objects.filter(
        user=request.user).values_list('author_id', flat=True)
    posts = Post.objects.filter(author_id__in=authors)
    paginator = Paginator(posts, POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'title': 'Избранное'
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    is_follower = Follow.objects.filter(user=user, author=author)
    if user != author and not is_follower.exists():
        Follow.objects.create(user=user, author=author)
    return redirect('posts:profile', username=author)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    is_follower = Follow.objects.filter(user=request.user, author=author)
    is_follower.delete()
    return redirect('posts:profile', username=author)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load static %}
{% block title %}
<title <title>Новый пост</title>
{% endblock %}
  <body>
    <header>
      {%include 'includes/header.html'%}
    </header>	   
    <main>
      {% block content %}
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                {% if is_edit %}
                Редактировать пост
                {% else %}
                Новый пост     
                {% endif %}     
              </div>
              <div class="card-body">
                {% if is_edit %}
                  <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_edit' post_id.pk %}">
                {% else %}
                  <form method="post" enctype="multipart/form-data" action="{% url 'posts:create_post' %}">
                {% endif %}
                  {% csrf_token %}        
                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      Текст поста                  
                      <span class="required text-danger" >*</span>                  
                    </label>
                    <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text">
                    </textarea>                
                    <small id="id_text-help" class="form-text text-muted">
                      Текст нового поста
                    </small>                  
                  </div>            
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      Group                  
                    </label>
                    {{ form.group }}
                    <small id="id_group-help" class="form-text text-muted">
                      Группа, к которой будет относиться пост
                    </small>
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_image">
                      Картинка                      
                    </label>
                    <input type="file" name="image" accept="image/*" class="form-control" id="id_image">                      
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                        Сохранить
                      {% else %}
                        Добавить
                      {% endif %}               
                    </button> 
                    {% if post.group %}   
                     <a href="{% url 'posts:group_list' post.group.slug  %}">все записи группы</a>
                    {% endif %}
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
  </body>
  {% endblock %}
</html>

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load static %}
{% block title %}
<title href="{% url 'Posts:index' %}">Подписки</title>
{% endblock %}
  <body>
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      {% block content %}
      {% include 'includes/switcher.html' %}
        {% for post in page_obj %}
        <ul>
          <li>
            <a href="{% url 'posts:profile' post.author %}">Автор: {{ post.author.get_full_name }}</a>
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
          <a href="{% url 'posts:post_detail' post.id %}"> Подробнее:
          </a>
        </ul>
        <article class="col-12 col-md-3">
          {% thumbnail post.image "500x400" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
        </article>
          <p>
          {{ post.text }}
          </p>
        {% if post.group %}   
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        {% endif %} 
        {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
        {% include 'posts/includes/paginator.html' %}
      {% endblock %}
    </main>
  </body>

yatube/templates/posts/group_list.html
{% extends 'base.html' %} 
{% load thumbnail %}
{% load static %}
{% block title %}
<title href="{% url 'Posts:index' %}">Записи сообщества {{ group.title }}
</title>
{% endblock %}
  <body>
    <header>
      {%include 'includes/header.html'%}{{ group.title }}
    </header>
    <main>
        <li>
       Описание {{ group.description }}
        </li>
      {% block content %}
        <h1>{{ group.title }}</h1>
        <p>{{ group.description }}</p>
        {% for post in posts %}
        <article>
          <ul>
            <li>
              <a href="{% url 'posts:profile' post.author %}">Автор: {{ post.author.get_full_name }}</a>
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
            <a href="{% url 'posts:post_detail' post.id %}"> Подробнее:
            </a>
          </ul>
          <article class="col-12 col-md-3">
            {% thumbnail post.image "500x400" crop="center" upscale=True as im %}
              <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
          </article>
            <p>
            {{ post.text }}
            </p>
        {% if not forloop.last %}<hr>{% endif %}
        {% empty %}
        <p> Если цикл пустой </p>
        {% endfor %}
        {% include 'posts/includes/paginator.html' %}
      {% endblock %}
    </main>      
  </body>

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load cache %}
{% load static %}
{% block title %}
<title href="{% url 'Posts:index' %}">Последние обновления на сайте
</title>
{% endblock %}
  <body>
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      {% block content %}
      {% include 'includes/switcher.html' %}
      {% cache 20 index_page %}
        {% for post in page_obj %}
        <ul>
          <li>
            <a href="{% url 'posts:profile' post.author %}">Автор: {{ post.author.get_full_name }}</a>
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
          <a href="{% url 'posts:post_detail' post.id %}"> Подробнее:
          </a>
        </ul>
        <article class="col-12 col-md-3">
          {% thumbnail post.image "500x400" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
        </article>
          <p>
          {{ post.text }}
          </p>
        {% if post.group %}   
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        {% endif %} 
        {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
        {% endcache %}
        {% include 'posts/includes/paginator.html' %}
      {% endblock %}
    </main>
  </body>

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% load static %}
{% block title %} <title>Пост {{post.text|truncatechars:30 }}</title> {% endblock %}
{% block content %}
  <body>       
    <main>
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
            {% if post.group %}
              <li class="list-group-item">
                Группа: {{ group.name }}
                <a href="{% url 'posts:group_list' post.group.slug %}">
                  все записи группы
                </a>
              </li>
            {% endif %}
              <li class="list-group-item">
                Автор: {{ post.author.get_full_name }}
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ posts_count }}</span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author%}">
                все посты пользователя
              </a>
            </li>
            {% if user == post.author %}
            <a class="btn btn-default" href="{% url 'posts:post_edit' post_id=post.pk %}"><span class="list-group-item">
              Редактировать запись</span></a>
          </ul>
          {% endif %}
        </aside>
        <article class="col-12 col-md-9">
          <p>
          {{ post.text }}
          </p>
          <p class="col-12 col-md-3">
            {% thumbnail post.image "500x400" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %} 
          </p>
        </article>
        {% if user.is_authenticated %}
        <div class="card my-4">
          <h5 class="card-header">Добавить комментарий:</h5>
          <div class="card-body">
            <form method="post" action="{% url 'posts:add_comment' post.id %}">
              {% csrf_token %}    
              <div class="form-group mb-2">
                <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text">
                </textarea>
              </div>
              <button type="submit" class="btn btn-primary">Отправить</button>
            </form>
            {% endif %}
          </div>
        </div>
        <div class="media mb-4">
          <div class="media-body">
            <h5 class="mt-0">
              {% for comment in comments %}
             <div class="media mb-4">
              <div class="media-body">
               <h5 class="mt-0">
               <a href="{% url 'posts:profile' comment.author.username %}">
                {{ comment.author.username }}
               </a>
               </h5>
              <p>
                {{ comment.text }}
              </p>
             </div>
            </div>
          {% endfor %} 
      </div> 
    </main>
  </body>
  {% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% load thumbnail %}
{% load static %}
{% block title %}<title>Профайл пользователя {{ author }}</title>{% endblock %}
{% block content %}
  <body>       
    <main>
      <div class="mb-5">      
        <h1>Все посты пользователя {{ author.first_name }} {{ author.last_name }} </h1>
        <h3>Всего постов: {{ posts_count }} </h3>
        {% if user != author%}
        {% if following %}
        <a
         class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_unfollow' author.username %}" role="button"
        >
         Отписаться
        </a>
        {% else %}
         <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' author.username %}" role="button"
          >
         Подписаться
        </a>
       {% endif %}
       {% endif %}
      </div>
        {% for post in page_obj %}
        <article>
          <ul>
            <li>
              Автор: {{ author.first_name }} {{ author.last_name }}
              <a href="{% url 'posts:profile' author %}">все посты пользователя</a>
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          <p>
            {{ post.text }}
          </p>
          <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
        </article>       
        {% if post.group %}   
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        <article class="col-12 col-md-3">
          {% thumbnail post.image "500x400" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
        </article>
      {% endif %} 
        <hr>
        {% endfor %}
        {% if not forloop.last %} <hr> {% endif %}
        {% include 'posts/includes/paginator.html' %}
      </div>
    </main>
  </body>
  {% endblock %}